### PR TITLE
A refactor

### PR DESCRIPTION
**Pull request by cpmachado**
* [feature/refactor] Add editorconfig

* [feature/refactor]: Update gitignore

* [feature/refactor] Split logic from index.js, get pretty print

* [feature/refactor] Refactor of library

* [feature/refactor] Update package.json

### CODE REVIEW

**Comment by cpmachado** [comment]
Closed the other, because this one is already with squash commit.

**Comment by cpmachado** [comment]
Found a bug I introduced, sorry -_-
Already fixed.

**Comment by cpmachado** [comment]
Already fixed

**Review by niabb — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
